/*
 * MySocial API
 *
 * Social network. There are users on the social network who can register, create, update and delete posts, get their own wall with posts, view walls with posts from other users, like and view statistics on posts in the form of the number of likes and views, as well as leave comments on posts and view them.
 *
 * API version: 1.0
 * Contact: neazhazha@edu.hse.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type User struct {
	// Must be unique in the system
	Login string `json:"login,omitempty"`
	// Can't be empty and will not change
	Password string `json:"password,omitempty"`
}
