/*
 * MySocial API
 *
 * Social network. There are users on the social network who can register, create, update and delete posts, get their own wall with posts, view walls with posts from other users, like and view statistics on posts in the form of the number of likes and views, as well as leave comments on posts and view them.
 *
 * API version: 1.0
 * Contact: neazhazha@edu.hse.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Information struct {
	// The user's name
	Name string `json:"name,omitempty"`
	// The user's surname
	Surname string `json:"surname,omitempty"`
	// The user's date of birth
	DateOfBirth string `json:"date_of_birth,omitempty"`
	// The user's mail
	Mail string `json:"mail,omitempty"`
	// The user's phone number
	PhoneNumber string `json:"phone_number,omitempty"`
}
