version: "3.8"

services:
  mongo:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - majorData:/data/db

  major:
    build:
      context: .
      dockerfile: ./cmd/major/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - task
      - statistic

  task:
    build:
      context: .
      dockerfile: ./cmd/task/Dockerfile
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      - cassandra1
      - cassandra2
      - cassandra3

  statistic:
    build:
      context: .
      dockerfile: ./cmd/statistic/Dockerfile
    restart: always
    ports:
      - "7070:7070"
    depends_on:
      - kafka

  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    hostname: cassandra1
    ports:
      - "9042:9042"
    environment: &environment
      CASSANDRA_SEEDS: "cassandra1,cassandra2"
      CASSANDRA_CLUSTER_NAME: MyTestCluster
      CASSANDRA_DC: DC1
      CASSANDRA_RACK: RACK1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128
  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    hostname: cassandra2
    ports:
      - "9043:9042"
    environment: *environment
    depends_on:
      cassandra1:
        condition: service_started
  cassandra3:
    image: cassandra:latest
    container_name: cassandra3
    hostname: cassandra3
    ports:
      - "9044:9042"
    environment: *environment
    depends_on:
      cassandra2:
        condition: service_started

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"

    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

volumes:
  majorData:
