version: '3.3'

services:
  mongo:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - majorData:/data/db
  major:
    image: golang:latest
    build:
      context: .
      dockerfile: ./cmd/major/Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - mongo
  task:
    image: golang:latest
    build:
      context: .
      dockerfile: ./cmd/task/Dockerfile
    ports:
      - '9090:9090'

volumes:
  majorData:
