version: '3.3'

services:
  mongo:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db

  major:
    image: golang:latest
    build:
      context: .
      dockerfile: cmd/major/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo

volumes:
  dbdata:
