/*
 * MySocial API
 *
 * Social network. There are users on the social network who can register, create, update and delete posts, get their own wall with posts, view walls with posts from other users, like and view statistics on posts in the form of the number of likes and views, as well as leave comments on posts and view them.
 *
 * API version: 1.0
 * Contact: neazhazha@edu.hse.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	swagger "github.com/ogen-go/ogen/major/go"
	"log"
	"net/http"
	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
)

func main() {
	log.Printf("Server started")

	router := swagger.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
